export const validGenericNames = [
	"mobile", "laptop", "headphone", "speaker", "charger", "power bank", "smartwatch", "earbud", "tablet", "television",
	"camera", "printer", "keyboard", "mouse", "monitor", "router", "webcam", "microphone", "usb drive", "hard drive",
	"ssd", "gaming console", "gaming accessory", "drone", "smart home device", "smart light", "smart plug", "doorbell",
	"security camera", "home theatre", "projector", "blender", "mixer grinder", "pressure cooker", "induction cooktop",
	"air fryer", "microwave", "refrigerator", "washing machine", "dishwasher", "vacuum cleaner", "iron", "water purifier",
	"geyser", "fan", "air cooler", "heater", "coffee maker", "toaster", "electric kettle", "juicer", "food processor",
	"cookware set", "frying pan", "saucepan", "cooker", "kitchen utensil", "dinner set", "glassware", "storage container",
	"lunch box", "water bottle", "thermos", "cutting board", "knife set", "peeler", "grater", "apparel", "t-shirt",
	"shirt", "jeans", "trouser", "dress", "saree", "kurti", "jacket", "sweater", "hoodie", "shorts", "skirt", "top",
	"sportswear", "swimwear", "underwear", "socks", "footwear", "shoes", "sneaker", "sandal", "slipper", "heels",
	"boot", "watch", "handbag", "backpack", "wallet", "belt", "sunglasses", "jewelry set", "earrings", "necklace",
	"bracelet", "ring", "perfume", "deodorant", "shampoo", "conditioner", "soap", "body wash", "lotion", "moisturizer",
	"face wash", "serum", "sunscreen", "makeup", "lipstick", "foundation", "mascara", "eyeliner", "nail polish",
	"hair dryer", "straightener", "curler", "trimmer", "shaver", "toothbrush", "toothpaste", "mouthwash", "hand sanitizer",
	"mask", "vitamins", "supplements", "protein powder", "ayurvedic product", "medical device", "thermometer", "bp monitor",
	"pulse oximeter", "first aid kit", "yoga mat", "dumbbell", "resistance band", "treadmill", "exercise bike",
	"fitness tracker", "sports shoe", "cricket bat", "football", "basketball", "badminton racket", "tennis racket",
	"sleeping bag", "tent", "camping gear", "gardening tool", "plant seed", "pot", "fertilizer", "pest control",
	"home decor", "curtain", "bedsheet", "cushion cover", "rug", "carpet", "photo frame", "wall art", "vase", "candle",
	"decorative lamp", "figurine", "artificial plant", "furniture", "sofa", "bed", "mattress", "dining table", "chair",
	"wardrobe", "bookshelf", "study table", "tv unit", "shoe rack", "book", "fiction book", "non-fiction book",
	"children's book", "textbook", "ebook reader", "dvd", "blu-ray", "cd", "vinyl record", "video game", "toy", "doll",
	"action figure", "building block", "board game", "puzzle", "remote control toy", "stuffed animal", "baby product",
	"diaper", "baby wipes", "baby food", "baby lotion", "baby shampoo", "baby soap", "pram", "stroller", "car seat",
	"crib", "baby carrier", "pet food", "pet toy", "pet grooming tool", "pet bed", "cat litter", "dog collar",
	"dog leash", "groceries", "staples", "snack", "beverage", "breakfast cereal", "cooking oil", "spices", "flour",
	"rice", "lentils", "sugar", "salt", "tea", "coffee", "chocolate", "biscuit", "chips", "noodle", "sauce", "jam",
	"honey", "dry fruit", "nut", "canned food", "frozen food", "cleaning supply", "detergent", "floor cleaner",
	"dishwashing liquid", "toilet cleaner", "glass cleaner", "brush", "mop", "dustbin", "tissue paper", "toilet paper",
	"paper towel", "stationery", "pen", "pencil", "notebook", "paper", "eraser", "sharpener", "scale", "calculator",
	"bag", "school bag", "office supply", "file folder", "stapler", "punch machine", "glue", "tape", "art supply",
	"paint", "brush set", "canvas", "drawing book", "craft kit", "musical instrument", "guitar", "drum set", "ukulele",
	"violin", "home improvement", "drill machine", "tool kit", "screwdriver", "hammer", "wrench", "adhesive",
	"lighting fixture", "bulb", "battery", "extension cord", "power strip", "vehicle accessory", "car charger",
	"car air freshener", "car cleaner", "bike helmet", "bike accessory", "luggage", "travel bag", "suitcase",
	"duffel bag", "travel pillow", "travel adapter", "gift set", "flower", "chocolate box", "greeting card", "voucher",
	"subscription", "software", "antivirus", "operating system", "utility software", "education course", "online class",
	"web hosting", "domain name", "digital product", "ebook", "music download", "movie download", "game download",
	"gift card", "furniture cover", "car cover", "bike cover", "umbrella", "raincoat", "sleeping mask", "earplugs",
	"travel neck pillow", "electric blanket", "heating pad", "massager", "humidifier", "dehumidifier", "air purifier",
	"air conditioner", "water dispenser", "cooler", "vacuum flask", "storage box", "basket", "hanger", "clothes rack",
	"laundry basket", "drying rack", "mirror", "clock", "photo album", "journal", "diary", "calendar", "planner",
	"desk organizer", "pen stand", "file cabinet", "shredder", "projector screen", "webcam cover", "screen protector",
	"laptop stand", "mobile stand", "ring light", "tripod", "microphone stand", "keyboard cover", "mouse pad",
	"webcam light", "usb hub", "cable organizer", "cable protector", "power adapter", "travel mug", "tumbler",
	"coaster", "tablecloth", "napkin", "placemat", "cutlery set", "chopsticks", "straw", "bottle opener", "can opener",
	"kitchen scale", "timer", "oven mitt", "apron", "dish towel", "cleaning cloth", "sponge", "scrubber", "broom",
	"dustpan", "wiper", "gloves", "disinfectant", "air freshener", "insect repellent", "candle holder",
	"incense stick", "aroma diffuser", "essential oil", "massage oil", "bath bomb", "bath salt", "loofah", "hair brush",
	"comb", "razor", "shaving cream", "aftershave", "hand cream", "foot cream", "lip balm", "body butter", "face mask",
	"hair mask", "sun hat", "scarf", "belt buckle", "tie", "cufflinks", "brooch", "keychain", "swimming goggles",
	"swim cap", "gym bag", "sports water bottle", "protein bar", "energy drink", "health supplement",
	"protein supplement", "fish oil", "multivitamin", "calcium supplement", "iron supplement", "zinc supplement",
	"vitamin c", "vitamin d", "b-complex", "probiotic", "prebiotic", "digestive enzyme", "sleep aid", "stress relief",
	"pain relief", "cold medicine", "fever medicine", "allergy medicine", "antiseptic", "bandage", "gauze",
	"cotton ball", "ointment", "spray", "hand wash", "sanitizer refill", "tissue box", "face towel", "bath towel",
	"hand towel", "door mat", "shoe mat", "car mat", "boot mat", "dash cam", "car vacuum cleaner", "tire inflator",
	"jump starter", "car perfume", "car polish", "car wax", "bike lock", "bike pump", "bike light", "cycle bell",
	"cycle stand"
];

export const validBrandNames = [
	"samsung", "apple", "oneplus", "xiaomi", "redmi", "mi", "iqoo", "realme", "vivo", "oppo",
	"motorola", "nokia", "lava", "infinix", "google", "nothing", "sony", "lg", "panasonic", "philips",
	"bajaj", "usha", "havells", "v-guard", "orient", "crompton", "bosch", "ifb", "whirlpool", "haier",
	"godrej", "kent", "eureka forbes", "prestige", "pigeon", "milton", "cello", "butterfly", "lifelong", "bajaj vacco",
	"fire-boltt", "noise", "boat", "portronics", "ambrane", "zebronics", "jbl", "anker", "soundcore", "skullcandy",
	"logitech", "hp", "dell", "asus", "lenovo", "acer", "msi", "apple", "amazon basics", "sony playstation",
	"wrogn", "puma", "adidas", "nike", "reebok", "sparx", "red tape", "bata", "campus", "asian",
	"liberty", "crocs", "woodland", "metro", "fila", "skechers", "hrx", "levis", "peter england", "allen solly",
	"van heusen", "roadster", "flying machine", "us polo", "tommy hilfiger", "dennis lingo", "bewakoof", "zara", "h&m", "max",
	"shining diva", "yellow chimes", "jpearls", "sukkhi", "aristocrat", "wildcraft", "american tourister", "skybags", "safari", "fastrack",
	"timex", "casio", "sonata", "titan", "noise", "fire-boltt", "apple watch", "boat watch", "gshock", "fitbit",
	"boldfit", "mivi", "realme buds", "anker", "intex", "micromax", "karbonn", "blaupunkt", "vu", "tcl"
];